### PR TITLE
Default `by` argument for `ard_*()` functions

### LINKED ISSUE #106: Should we use this default value for our `by` arguments? `by = dplyr::group_vars(data)`

### PR DESCRIPTION
**Pull request by bzkrouse**
**What changes are proposed in this pull request?**
* Style this entry in a way that can be copied directly into `NEWS.md`. (#1, @ddsjoberg)

**Reference GitHub issue associated with pull request.** _e.g., 'closes #1'_
Resolves #106 

--------------------------------------------------------------------------------

Pre-review Checklist (if item does not apply, mark is as complete)
- [x] **All** GitHub Action workflows pass with a :white_check_mark:
- [x] PR branch has pulled the most recent updates from master branch: `usethis::pr_merge_main()`
- [x] If a bug was fixed, a unit test was added.
- [x] Code coverage is suitable for any new functions/features (generally, 100% coverage for new code): `devtools::test_coverage()`

Reviewer Checklist (if item does not apply, mark is as complete)

- [x] If a bug was fixed, a unit test was added.
- [x] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [x] Code coverage is suitable for any new functions/features: `devtools::test_coverage()`
- [x] Request a reviewer

When the branch is ready to be merged:
- [x] Update `NEWS.md` with the changes from this pull request under the heading "`# cards (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [x] Increment the version number using `usethis::use_version(which = "dev")`
- [x] Run `usethis::use_spell_check()` again
- [x] Approve Pull Request
- [x] Merge the PR. Please use "Squash and merge" or "Rebase and merge".

### CODE REVIEW

**Comment by bzkrouse** [comment]
@ddsjoberg Do you think this is enough info for the user?

**Comment by ddsjoberg** [comment]
I think if we add it to these functions, we should also add it to these functions? What do you think?

```r
ard_hierarchical()
ard_hierarchical_count()
ard_dichotomous()
ard_missing()
ard_complex()
```

**Comment by bzkrouse** [comment]
@ddsjoberg Updated! Please have another look :)

**Review by ddsjoberg — APPROVED** [review]
looks great!! 🎈 🎈 🎈

**Pull request merged**
