### PR TITLE
Added functions for mock tables

### LINKED ISSUE #256: Table Shell Helpers
I am thinking about ways to make table shells.

- Would a function that populates an empty ARD be helpful? This would be more helpful for the non-standard methods.
- A way to swap out default formatting functions for functions that just return `xx.x` or `xx`.
- Anything else?

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**
* Added functions `mock_continuous()`, `mock_categorical()`, `mock_dichotomous()`, `mock_missing()`, `mock_attributes()` to build ARDs in the absence of a data frame. Where applicable, the formatting functions are set to return `'xx'` or `'xx.x'` to aid in the construction of mock tables or table shells. (#256)

**Reference GitHub issue associated with pull request.** _e.g., 'closes #<issue number>'_
closes #256

--------------------------------------------------------------------------------

Pre-review Checklist (if item does not apply, mark is as complete)
- [x] **All** GitHub Action workflows pass with a :white_check_mark:
- [x] PR branch has pulled the most recent updates from master branch: `usethis::pr_merge_main()`
- [x] If a bug was fixed, a unit test was added.
- [x] Code coverage is suitable for any new functions/features (generally, 100% coverage for new code): `devtools::test_coverage()`
- [x] Request a reviewer

Reviewer Checklist (if item does not apply, mark is as complete)

- [ ] If a bug was fixed, a unit test was added.
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features: `devtools::test_coverage()`

When the branch is ready to be merged:
- [ ] Update `NEWS.md` with the changes from this pull request under the heading "`# cards (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [ ] **All** GitHub Action workflows pass with a :white_check_mark:
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge" or "Rebase and merge".

### CODE REVIEW

**Comment by bzkrouse** [comment]
These are really nice!!! Just one question:
What do you think about adding a `fmt_fn` argument? (seems like mock_*() |> update_ard_fmt_fn() works well)

And 2 other related questions but they may very well be in the future plans:)
1. This idea from the issues: WE could add class mock-card to these objects, and perhaps include functions that could convert mock ARD into proper code to create the ARD.
2. mock_hierarchical /mock_stack functions?

**Comment by ddsjoberg** [comment]
Thank you @bzkrouse for the review! ❤️ 

> These are really nice!!! Just one question: What do you think about adding a `fmt_fn` argument? (seems like mock_*() |> update_ard_fmt_fn() works well)

I struggled with this too! Whether to add it or not. Ultimately I think that adding it may be confusing because I think a function that always returns `"xx.x"` may be non-intuitive for users, and if they want to change it they can use `update_ard_fmt_fn()`. If we go that route, I should add an example modifying the formatting fn to the help page.

One other idea I was toying with was adding an argument where the users specify the number of digits they want to see a statistic rounded to, and we convert that into a function like `\(x) "xx.xx"` if they requested 2 digits.

> 1. This idea from the issues: WE could add class mock-card to these objects, and perhaps include functions that could convert mock ARD into proper code to create the ARD.

I think this is a good idea. But didn't want to implement when i was writing. I think we should add an issue to make this update in the future.

> 2. mock_hierarchical /mock_stack functions?

Yes! but let's create an issue to add them later?

**Comment by ddsjoberg** [comment]
@bzkrouse notes from meeting

1. For now, not adding the argument, but update the example to show users how to update the formatting function. Will perhaps add an argument in the future.
2. Converting mock tables into code to create that table: we'll create an issue and anyone who may need this can develop further.
3. We'll open an issue for `mock_hierarchicial()`/`ard_stack()` to add later

**Comment by ddsjoberg** [comment]
> @bzkrouse notes from meeting
> 
> 1. For now, not adding the argument, but update the example to show users how to update the formatting function. Will perhaps add an argument in the future.
> 2. Converting mock tables into code to create that table: we'll create an issue and anyone who may need this can develop further.
> 3. We'll open an issue for `mock_hierarchicial()`/`ard_stack()` to add later

Example updated and new issue opened for potential updated to the mocking functions

**Pull request merged**
